---
ls:
  .puml: kebab-case
  .md: kebab-case | SCREAMING_SNAKE_CASE

  .conf: kebab-case
  .json: kebab-case
  .yml: kebab-case
  .yaml: kebab-case

  .sh: kebab-case

  .js: kebab-case
  .gatling.js: kebab-case

  Dockerfile: PascalCase

  .env: lowercase
  .dockerignore: lowercase
  .folderslintrc: lowercase
  .gitignore: lowercase
  .gitkeep: lowercase
  .shellcheckrc: lowercase

ignore:
  # commons
  - .git
  - .idea
  - .vscode
  - node_modules
  - target

  # linter definitions etc.
  - .hadolint.yml
  - .ls-lint.yml
  - .markdownlint.yml
  - .yamllint.yml
  - .pre-commit-config.yaml
  - .releaserc
  - .release.sh
