---
volumes:

  project-root-volume:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind


services:

  cleanup:
    container_name: ${COMPOSE_PROJECT_NAME}-cleanup
    image: alpine:latest
    volumes: &volumes
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - project-root-volume:/workspaces/poc-load-testing
    working_dir: &default-workdir /workspaces/poc-load-testing
    command: |
      rm -rf target
    tty: &tty true

  lint-yaml:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-yaml
    image: cytopia/yamllint:latest
    volumes: *volumes
    working_dir: *default-workdir
    command: .
    tty: *tty

  lint-workflows:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-workflows
    image: rhysd/actionlint:latest
    volumes: *volumes
    working_dir: *default-workdir
    command: -color
    tty: *tty

  lint-filenames:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-filenames
    image: lslintorg/ls-lint:1.11.2
    volumes: *volumes
    working_dir: *default-workdir
    tty: *tty

  lint-folders:
    container_name: ${COMPOSE_PROJECT_NAME}-lint-folders
    image: sommerfeldio/folderslint:latest
    volumes: *volumes
    working_dir: *default-workdir
    command: .
    tty: *tty

  docs-build:
    container_name: ${COMPOSE_PROJECT_NAME}-docs-build
    image: &docs-image sommerfeldio/mkdocs:latest
    user: 1000:1000
    volumes: *volumes
    working_dir: *default-workdir
    command: build
    tty: *tty
    depends_on:
      cleanup:
        condition: service_completed_successfully

  docs-dev-server:
    container_name: ${COMPOSE_PROJECT_NAME}-docs-dev-server
    image: *docs-image
    volumes: *volumes
    working_dir: *default-workdir
    ports:
      - 3080:8000
    tty: *tty

  system-under-test:
    container_name: ${COMPOSE_PROJECT_NAME}-system-under-test
    image: springcommunity/spring-framework-petclinic:6.1.2
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      cleanup:
        condition: service_completed_successfully

  gatling:
    container_name: ${COMPOSE_PROJECT_NAME}-gatling
    image: eclipse-temurin:23.0.1_11-jdk-noble # noble = ubuntu 24.04
    user: 1000:1000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - project-root-volume:/workspaces/poc-load-testing
      - /home/vscode/.m2:/home/ubuntu/.m2
    working_dir: *default-workdir
    environment:
      SYSTEM_UNDER_TEST: http://system-under-test:8080
    command: ./mvnw gatling:test
    depends_on:
      system-under-test:
        condition: service_healthy
