---
site_name: PoC Load Testing
site_url: https://www.sommerfeld.io
site_author: Sebastian Sommerfeld
site_description: >-
  PoC Load Testing for sommerfeld.io projects.

repo_name: sommerfeld-io/poc-load-testing
repo_url: https://github.com/sebastian-sommerfeld-io/poc-load-testing

copyright: Copyright &copy; 2024 Sommerfeld.io

docs_dir: docs
site_dir: target/docs/site

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - content.code.copy
    - content.tabs.link
    # - navigation.tabs
    - navigation.footer
    # - navigation.sections
    - navigation.expand
    - navigation.tracking

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - kroki:
  - search:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sebastian-sommerfeld-io/poc-load-testing

nav:
  - Home: index.md
